development:
  omniauth_provider_key: <%= ENV['OMNIAUTH_PROVIDER_KEY'] %>
  omniauth_provider_secret: <%= ENV['OMNIAUTH_PROVIDER_SECRET'] %>
  google_provider_key: <%= ENV['GOOGLE_PROVIDER_KEY'] %>
  google_provider_secret: <%= ENV['GOOGLE_PROVIDER_SECRET'] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio_sid: <%= ENV['TWILIO_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_num: <%= ENV['TWILIO_NUM'] %>
  google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>

test:
  secret_key_base: rake secret

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV['OMNIAUTH_PROVIDER_KEY'] %>
  omniauth_provider_secret: <%= ENV['OMNIAUTH_PROVIDER_SECRET'] %>
  google_provider_key: <%= ENV['GOOGLE_PROVIDER_KEY'] %>
  google_provider_secret: <%= ENV['GOOGLE_PROVIDER_SECRET'] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio_sid: <%= ENV['TWILIO_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_num: <%= ENV['TWILIO_NUM'] %>
  google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
